added Homework_2, added 18 new files
UniAleks/Courses pull request #2
Opened 2022-11-22 07:34 UTC by UniAleks

2022-11-22 09:57 UTC, YeaaaaH commented on Homework2/TaskFour.java
> +        System.out.println(Math.pow(sum,square));
a2+b2+c2 != (a+b+c)2

2022-11-22 10:00 UTC, YeaaaaH commented on Homework2/TaskNine.java
> +        System.out.println(mas);
you don't need this line

2022-11-22 10:00 UTC, YeaaaaH commented on Homework2/TaskNine.java
> +        System.out.println(mas);
you don't need this line

2022-11-22 10:03 UTC, YeaaaaH commented on Homework2/TaskOne.java
> +        int sum = IntStream.of(mas).sum();
this function is not returning sum of absolute values

2022-11-22 10:06 UTC, YeaaaaH commented on Homework2/TaskSeven.java
> +        String Str = "753";
variables should be in lowerCase according to Naming Conventions

2022-11-22 10:08 UTC, YeaaaaH commented on Homework2/TaskThree.java
> +        double mas[] = {1, 7, 3.43, 2.8, 4.75, 3.33, 9.5, 21};
you don't need this array, get element from input stream

2022-11-22 10:09 UTC, YeaaaaH requested changes
need to fix comments

2022-11-30 13:41 UTC, UniAleks commented on Homework2/TaskNine.java
> +        System.out.println(mas);
fixed

2022-11-30 13:42 UTC, merged